### PR TITLE
client/connection: conn.Me(): do not override cfg.Me or it is lost for next reconnect

### PR DESCRIPTION
**Pull request by StalkR**
When we disconnect:
1) shutdown() calls initialise() which wipes the state: https://github.com/fluffle/goirc/blob/master/client/connection.go#L214
2) Me() always takes it from the state: https://github.com/fluffle/goirc/blob/master/client/connection.go#L174
So in the end we've lost Me.Nick, Me.Ident, Me.Name which are needed for register: https://github.com/fluffle/goirc/blob/master/client%2Fhandlers.go#L39

This manifests as:
```
I0401 01:21:48.701247   32292 connection.go:248] irc.Connect(): Connecting to irc.stalkr.net:6697 with SSL.
I0401 01:21:49.715255   32292 connection.go:384] -> NICK godev
I0401 01:21:49.715401   32292 connection.go:384] -> USER  12 * :
I0401 01:21:49.715663   32292 connection.go:321] <- :irc.stalkr.net NOTICE AUTH :*** Looking up your hostname...
I0401 01:21:49.715679   32292 connection.go:321] <- :irc.stalkr.net NOTICE AUTH :*** Found your hostname (cached)
I0401 01:21:49.755733   32292 connection.go:321] <- PING :BF0EB246
I0401 01:21:49.755759   32292 connection.go:321] <- :irc.stalkr.net 461 godev USER :Not enough parameters
I0401 01:21:49.755906   32292 connection.go:384] -> PONG :BF0EB246
```

### CODE REVIEW

**Comment by fluffle** [comment]
Wipe() doesn't wipe Me, so I am a little confused about this. I can see ident and name are definitely missing from the USER line, but the NICK line is correct. I am somewhat ashamed to admit I've never used the state tracking code in anger myself, so you're essentially QAing it for me.

I think the problem is a little more subtle: that information is lost as soon as state tracking is enabled, because I never actually give it to the state tracker. Oops. Let me push a fix I think is more correct to a test branch and you can see if it fixes your issue.

**Comment by fluffle** [comment]
Well, I said a test branch but I'm pretty sure I'm right because the test changes fail unless the change to connection.go is made, so it went to master.

**Comment by StalkR** [comment]
Oh, I like state tracking! didn't realize it was that experimental :)

Trying your change on head.

**Comment by StalkR** [comment]
Fix confirmed! Thanks :)

**Pull request closed without merging**
