### PR TITLE
Syntax highlighting

### PR DESCRIPTION
**Pull request by bob-smith**
Markdown knows about golang, so use that for the code sample

[Review on Reviewable](https://reviewable.io/reviews/fluffle/goirc/83)

### CODE REVIEW

**Comment by fluffle** [comment]
Ah shit, I merged PRs in the wrong order. Can you rebase your change onto current master with:

```sh
git checkout master
git pull
git checkout patch-1
git rebase master
git push --force
```
Please?

**Comment by bob-smith** [comment]
rebased

**Comment by fluffle** [comment]
Hmm, something has gone wrong here -- I shouldn't see commits that I've already merged into master in this PR. You might need to create a new branch and a new PR to make this clean.

**Comment by bob-smith** [comment]
https://github.com/fluffle/goirc/pull/84

**Comment by bob-smith** [comment]
Closed as this was done in https://github.com/fluffle/goirc/pull/84

**Pull request closed without merging**
