### PR TITLE
Handler timeout

### PR DESCRIPTION
**Pull request by sadbox**
This will (optionally) set an upper limit on fgHandlers and intHandlers so that if something breaks in one of them the IRC client won't hang indefinitely waiting for the DISCONNECTED event.

---
This change is [Reviewable](https://reviewable.io/reviews/fluffle/goirc/101)

### CODE REVIEW

**Comment by sadbox** [comment]
Here's an example where I intentionally created an infinite loop inside a fghandler.

```text
I0531 21:30:32.577515    6987 dispatch.go:148] Starting main.showWeather handler for event PRIVMSG
I0531 21:30:32.577520    6987 dispatch.go:150] Finished main.showWeather handler for event PRIVMSG
I0531 21:30:32.577530    6987 dispatch.go:148] Starting main.showQuote handler for event PRIVMSG
I0531 21:30:32.577535    6987 dispatch.go:150] Finished main.showQuote handler for event PRIVMSG
I0531 21:30:32.577544    6987 dispatch.go:148] Starting main.main.func4 handler for event PRIVMSG
I0531 21:30:32.577560    6987 dispatch.go:148] Starting main.configCommands handler for event PRIVMSG
I0531 21:30:32.577568    6987 dispatch.go:150] Finished main.configCommands handler for event PRIVMSG
I0531 21:30:32.582107    6987 dispatch.go:150] Finished main.logMessage handler for event PRIVMSG
E0531 21:31:32.577306    6987 dispatch.go:172] Timeout waiting for handlers to complete
I0531 21:31:32.577345    6987 connection.go:585] irc.Close(): Disconnected from server.
I0531 21:31:32.577477    6987 connection.go:591] irc.Close(): Draining
I0531 21:31:32.577484    6987 connection.go:594] irc.Close(): Waiting for waitgroup
E0531 21:31:32.577572    6987 connection.go:435] irc.recv(): read tcp [2600:3c00::f03c:91ff:fe6e:3a69]:43296->[2600:3c02::f03c:91ff:fe59:7d2e]:6697: use of closed network connection
I0531 21:31:32.577583    6987 connection.go:599] irc.Close(): Dispatching Disconnect
I0531 21:31:32.577633    6987 dispatch.go:148] Starting main.main.func3 handler for event DISCONNECTED
disconnected!I0531 21:31:32.577643    6987 dispatch.go:150] Finished main.main.func3 handler for event DISCONNECTED
```

**Comment by fluffle** [comment]
I'm not completely averse to the sentiment here, but:

1. Changing the default behaviour is not ok and may surprise people using the library, this needs to default to not having a timeout.
2. The timeout should be moved up one level so it is in *Conn.dispatch(). At the moment there are effectively three separate timeouts, one for each handlerset, and this will result in background handlers being terminated after the timeout duration (if set) when they don't need to be.
3. Forcibly disconnecting the IRC client when one handler gets stuck doing a thing is not the right approach. Logging an error is fine, but it's not unreasonable to assume that this could be used to prevent the client from being forcibly disconnected by the server because it was unresponsive by e.g. setting a single-digit-seconds timeout that acted as a watchdog.
4. This doesn't actually stop the handler from running, it just returns control to the dispatch loop. Thus it effectively "backgrounds" the stuck handler, which may or may not be desirable behaviour to the library user. 
5. I'd rather there weren't two debug lines around every handler dispatch, eww.

Lastly, please convince me that this level of second-guessing library users and their ability to not accidentally an infinite loop into their handlers is warranted. I'm not sure the client ought to be providing this level of hand-holding to users.

**Comment by sadbox** [comment]
1. Will do

2. Also noted
 
3+4. The idea is to either provide protocol consistency (per the docs) or to kill the connection. It also seems like a bad idea to let jobs hang out in the background indefinitely. Another option is essentially turning all FGHandlers in to BGHandlers if the timeout is exceeded and logging it.

5. I think it would be pretty easy to track which handlers haven't finished and log the actual problem. Can do.

re: Why I think this is a good thing.
There are lots of ways to unintentionally hit unbounded wait times. Accidentally-an-infinite-loop is not what I'm worried about. Logging an connection to a database, and that hanging for unbounded lengths of time is (this is what bit me). This also applies to anything that makes web requests, etc.   The problem is also that when you hit one of these issues, you don't just keep chugging along. The library will never process another event, including the DISCONNECT one.  

If you'd like me to make the changes I'd be happy to, else I'm also happy to implement it on my side.

**Comment by fluffle** [comment]
Re 3+4: the code as it is currently will leave the handlers running in the background indefinitely (if they are infinite loops), but I'm not really sure if it's *possible* to do anything else. Once the goroutine the handler code is launched in is running that handler code, the library has no way of shooting that goroutine in the head.

Explicitly styling this as "automatically backgrounding foreground handlers that tie up the event loop for more than N seconds" sounds reasonable to me. My first assertion would be that many things don't need protocol consistency -- if you're simply listening for a PRIVMSG then hitting a DB and responding with another PRIVMSG you are probably fine. But if you are tracking state for the channel and using it for authentication then that's a different matter. The default is to add foreground handlers, so the door is left open for people to shoot themselves in the foot.

**Comment by sadbox** [comment]
You are correct that it is not possible to kill a goroutine externally.  That leaves us with either bailing out or continuing with an error.  

My main concern with just backgrounding things that exceed the threshold is that it will be a rather annoying-to-debug (and surprising) mode of operation for anyone that does require protocol consistency. I agree that it's not extremely common to need it, but essentially turning it off seems like a worse idea to me.

**Comment by fluffle** [comment]
Sorry for the hiatus.

If you don't think that "just backgrounding things" is a good idea, but it's the only solution that is technically feasible given how goroutines work and how unkillable they are, then this is a non-starter. I think it's up to the library user to be responsible about not doing blocking work in a foreground handler.

**Pull request closed without merging**
