### PR TITLE
Negotiate capabilities during registration

### PR DESCRIPTION
**Pull request by ostafen**
Hi, I wrote a sketch for issue #77. I expect feedback before finalizing it :)

---
This change is [Reviewable](https://reviewable.io/reviews/fluffle/goirc/116)

### CODE REVIEW

**Comment by fluffle** [comment]
___
*[client/handlers.go, line 87 at r1](https://reviewable.io/reviews/fluffle/goirc/116#-MxhvTuABCaucMqpyFdG:-MxhvTuABCaucMqpyFdH:b-8imu2t) ([raw file](https://github.com/fluffle/goirc/blob/abfcc6aac2d081744d04b65ca0600dfde197f9c1/client/handlers.go#L87)):*
> ```Go
> 
> type capSet struct {
> 	caps map[string]struct{}
> ```

I would prefer a `map[string]bool` for code readability here, because of the convenience of nonexistent key returning false. Saving 4 bytes per map entry is not worth the effort when the map won't have more than a few tens of entries at the absolute maximum.

**Review by fluffle — CHANGES_REQUESTED** [review]
Ugh. Sorry about the errant comment, it has been a while since I used reviewable and I pressed the wrong button /o\

The general structure looks good -- I think you should be able to extend what's here to version 302 capability negotiation without having to rewrite things. Tests would be nice, during your finalization :-)

> *[Reviewable](https://reviewable.io/reviews/fluffle/goirc/116#-:-Mxi-7TDA9kvuYDwCxhI:b-f9le9s)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @fluffle and @ostafen)

___
*[client/connection.go, line 146 at r1](https://reviewable.io/reviews/fluffle/goirc/116#-MxhwUpQ1yCDIojJcCkc:-MxhwUpQ1yCDIojJcCkd:bmwzspt) ([raw file](https://github.com/fluffle/goirc/blob/abfcc6aac2d081744d04b65ca0600dfde197f9c1/client/connection.go#L146)):*
> ```Go
> 		SplitLen:                    defaultSplit,
> 		Timeout:                     60 * time.Second,
> 		EnableCapabilityNegotiation: true,
> ```

Please don't default this to true until the code has been live for a while for others to test.

On the other hand, providing a default list of Capabilities to request (i.e. the ones supported by the client) when this *is* set to true seems like a good idea.
___
*[client/connection.go, line 309 at r1](https://reviewable.io/reviews/fluffle/goirc/116#-MxhxQ-g2rs6QgSZMWTG:-MxhxQ-g2rs6QgSZMWTH:bd4i6ef) ([raw file](https://github.com/fluffle/goirc/blob/abfcc6aac2d081744d04b65ca0600dfde197f9c1/client/connection.go#L309)):*
> ```Go
> // SupportsCapability returns true if the server supports the given capability.
> func (conn *Conn) SupportsCapability(cap string) bool {
> 	return conn.currCaps.Has(cap)
> ```

I think you wanted supportedCaps here.
___
*[client/handlers.go, line 41 at r1](https://reviewable.io/reviews/fluffle/goirc/116#-MxhxtIS3iqazfAyv9_D:-MxhxtIS3iqazfAyv9_E:b-qt7voc) ([raw file](https://github.com/fluffle/goirc/blob/abfcc6aac2d081744d04b65ca0600dfde197f9c1/client/handlers.go#L41)):*
> ```Go
> func (conn *Conn) h_REGISTER(line *Line) {
> 	if conn.cfg.EnableCapabilityNegotiation {
> 		conn.Cap(CAP_LS)
> ```

The spec (https://ircv3.net/specs/extensions/capability-negotiation.html) allows for versioned capability negotiation. Do you intend to support this? At the moment I'm guessing not (or at least in a future PR), but it'd be good to know for sure.



_Code quote:_
```Go
conn.Cap(CAP_LS)
```
___
*[client/handlers.go, line 65 at r1](https://reviewable.io/reviews/fluffle/goirc/116#-MxhzoJL1kRpF8gHWYnf:-MxhzoJL1kRpF8gHWYng:b-v8o552) ([raw file](https://github.com/fluffle/goirc/blob/abfcc6aac2d081744d04b65ca0600dfde197f9c1/client/handlers.go#L65)):*
> ```Go
> 
> 	if len(reqCaps) > 0 {
> 		conn.Cap(CAP_REQ, reqCaps...)
> ```

Will the Cap command support splitting reqCaps over multiple lines, when it is implemented?
___
*[client/handlers.go, line 110 at r1](https://reviewable.io/reviews/fluffle/goirc/116#-MxhzAVQ9dDaAo5uLHYz:-MxhzAVQ9dDaAo5uLHZ-:b-2iosii) ([raw file](https://github.com/fluffle/goirc/blob/abfcc6aac2d081744d04b65ca0600dfde197f9c1/client/handlers.go#L110)):*
> ```Go
> }
> 
> // Handler for capability negotiation commands.
> ```

I assume an h_410 is part of the finalization plan?

**Comment by ostafen** [comment]
Thank you for the review.

- "I think you should be able to extend what's here to version 302 capability negotiation without having to rewrite things. Tests would be nice, during your finalization": I would open a separate issue/PR for versioned capability negotiation.
 
- "On the other hand, providing a default list of Capabilities to request (i.e. the ones supported by the client) when this is set to true seems like a good idea.": yes, definitely, I will add a list of default capability to request, even if, for now it would be empty, I guess.

- "Will the Cap command support splitting reqCaps over multiple lines, when it is implemented?": I simply used the Cap command the was already implemented, so I didn't take care of splitting. However, it is a good idea, I will implement line splitting.

- "I assume an h_410 is part of the finalization plan?": Yes, it is. I'm undecided about making the behaviour of this handler. Maybe, reporting a warning and sending a CAP END could be a good choice. What do you say?

**Review by fluffle — CHANGES_REQUESTED** [review]
Please use reviewable, it'll make the code review process way nicer! You can respond to individual comments and see a highlighted side-by-side code diff with the comments inline. It uses your Github credentials via OAuth.

Logging an warning for the invalid CAP command should be enough for the 410 handler. Reading the spec it seems that 410s are only for invalid top-level CAP commands. You probably need to handle the CAP NAK response to ensure that a NAK still results in a CAP END though.

> *[Reviewable](https://reviewable.io/reviews/fluffle/goirc/116#-:-MxkAXN0-KumAwIxKTks:b-8vcjup)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @fluffle and @ostafen)

___
*[client/commands.go, line 90 at r2](https://reviewable.io/reviews/fluffle/goirc/116#-Mxk65E2CVdqvMeRJ2Vi:-Mxk65E2CVdqvMeRJ2Vj:b-ap2ngk) ([raw file](https://github.com/fluffle/goirc/blob/b619c78dfa84485b8a58becf93872230a5a4e69a/client/commands.go#L90)):*
> ```Go
> // and returns a list of commands of the same form
> // where the len of each command doesn't exceed splitLen
> func splitCommand(cmdPrefix string, args []string) []string {
> ```

Your algorithm should work so I don't want you to drop it and do things my way. But, here's how I'd have approached this:

```go
partitioned := [][]string{}
remaining := splitLen - len(cmdPrefix) - 1
start := 0

for i, arg := range args {
    remaining = remaining - len(arg) - 1
    if remaining < 0 {
        partitioned = append(partitioned, args[start:i])
        start = i
        remaining = splitLen - len(cmdPrefix) - 1
    }
}
partitioned = append(partitioned, args[start:i])

cmds := make([]string, len(partitioned))
for i, part := range partitioned {
    cmds[i] = strings.Join(append([]string{cmdPrefix}, part...), " ")
}
return cmds
```

I'm not saying my way is any better or worse, but I thought it might make for interesting discussion.



_Suggestion:_
```Go
splitCommand	
```
___
*[client/commands.go, line 95 at r2](https://reviewable.io/reviews/fluffle/goirc/116#-Mxk5VE46br7j9H2xHOb:-Mxk5VE46br7j9H2xHOc:b-6ilbct) ([raw file](https://github.com/fluffle/goirc/blob/b619c78dfa84485b8a58becf93872230a5a4e69a/client/commands.go#L95)):*
> ```Go
> 	i := 0
> 	for i < len(args) {
> 		currCmd := cmdPrefix + args[i]
> ```

Missing a space here between cmdPrefix and args[i]. Also, please write tests for this function, they will catch bugs like this easily.
___
*[client/commands.go, line 98 at r2](https://reviewable.io/reviews/fluffle/goirc/116#-Mxk44bX8349J-cDWDer:-Mxk44bX8349J-cDWDes:b-u2b9qe) ([raw file](https://github.com/fluffle/goirc/blob/b619c78dfa84485b8a58becf93872230a5a4e69a/client/commands.go#L98)):*
> ```Go
> 		i++
> 
> 		for i < len(args) && len(currCmd) < 50 {
> ```

You should test len(currCmd) + len(args[i]) +1 does not exceed the limit; currently if args[i] is very long it will be appended and exceed the limit. Figuring out what to do when len(args[i]) > splitLen is left as an exercise for the reader ;-)
___
*[client/handlers.go, line 41 at r1](https://reviewable.io/reviews/fluffle/goirc/116#-MxhxtIS3iqazfAyv9_D:-Mxk9krt2AnpTuI6EyGk:b-oko0mp) ([raw file](https://github.com/fluffle/goirc/blob/abfcc6aac2d081744d04b65ca0600dfde197f9c1/client/handlers.go#L41)):*
<details><summary><i>Previously, fluffle (Alex Bee) wrote…</i></summary><blockquote>

The spec (https://ircv3.net/specs/extensions/capability-negotiation.html) allows for versioned capability negotiation. Do you intend to support this? At the moment I'm guessing not (or at least in a future PR), but it'd be good to know for sure.
</blockquote></details>

Coming in a future PR.
___
*[client/handlers.go, line 110 at r1](https://reviewable.io/reviews/fluffle/goirc/116#-MxhzAVQ9dDaAo5uLHYz:-MxkA36Y1yGeqfhPU3KL:bejxsqf) ([raw file](https://github.com/fluffle/goirc/blob/abfcc6aac2d081744d04b65ca0600dfde197f9c1/client/handlers.go#L110)):*
<details><summary><i>Previously, fluffle (Alex Bee) wrote…</i></summary><blockquote>

I assume an h_410 is part of the finalization plan?
</blockquote></details>

Also this needs a relatively exhaustive test to ensure the negotiation state machine is followed correctly.

**Review by fluffle — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/fluffle/goirc/116)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @fluffle and @ostafen)

___
*[client/commands.go, line 95 at r2](https://reviewable.io/reviews/fluffle/goirc/116#-Mxk5VE46br7j9H2xHOb:-MxkCk2t1oR3f-M7jJoM:b-zm1dk) ([raw file](https://github.com/fluffle/goirc/blob/b619c78dfa84485b8a58becf93872230a5a4e69a/client/commands.go#L95)):*
<details><summary><i>Previously, fluffle (Alex Bee) wrote…</i></summary><blockquote>

Missing a space here between cmdPrefix and args[i]. Also, please write tests for this function, they will catch bugs like this easily.
</blockquote></details>

Argh, and now I realise it shouldn't be there because your cmdPrefix ends  with ":". Sorry! I'd still like tests though :-)

**Review by ostafen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/fluffle/goirc/116)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @fluffle and @ostafen)

___
*[client/commands.go, line 90 at r2](https://reviewable.io/reviews/fluffle/goirc/116#-Mxk65E2CVdqvMeRJ2Vi:-MxkG6qg4qvi4OV30a-5:b-5vgq37) ([raw file](https://github.com/fluffle/goirc/blob/b619c78dfa84485b8a58becf93872230a5a4e69a/client/commands.go#L90)):*
<details><summary><i>Previously, fluffle (Alex Bee) wrote…</i></summary><blockquote>

Your algorithm should work so I don't want you to drop it and do things my way. But, here's how I'd have approached this:

```go
partitioned := [][]string{}
remaining := splitLen - len(cmdPrefix) - 1
start := 0

for i, arg := range args {
    remaining = remaining - len(arg) - 1
    if remaining < 0 {
        partitioned = append(partitioned, args[start:i])
        start = i
        remaining = splitLen - len(cmdPrefix) - 1
    }
}
partitioned = append(partitioned, args[start:i])

cmds := make([]string, len(partitioned))
for i, part := range partitioned {
    cmds[i] = strings.Join(append([]string{cmdPrefix}, part...), " ")
}
return cmds
```

I'm not saying my way is any better or worse, but I thought it might make for interesting discussion.
</blockquote></details>

I think both solutions are good in terms of readability. I would go for my solution only for a matter of compactness and because I don't really like dealing with bidimensional slices when possible.
___
*[client/commands.go, line 95 at r2](https://reviewable.io/reviews/fluffle/goirc/116#-Mxk5VE46br7j9H2xHOb:-MxkFvUg5lKMhLOzFp93:bt45zry) ([raw file](https://github.com/fluffle/goirc/blob/b619c78dfa84485b8a58becf93872230a5a4e69a/client/commands.go#L95)):*
<details><summary><i>Previously, fluffle (Alex Bee) wrote…</i></summary><blockquote>

Argh, and now I realise it shouldn't be there because your cmdPrefix ends  with ":". Sorry! I'd still like tests though :-)
</blockquote></details>

Yes, it was done precisely for that
___
*[client/commands.go, line 98 at r2](https://reviewable.io/reviews/fluffle/goirc/116#-Mxk44bX8349J-cDWDer:-MxkFJYBAWWS_XAWT45G:bl53opj) ([raw file](https://github.com/fluffle/goirc/blob/b619c78dfa84485b8a58becf93872230a5a4e69a/client/commands.go#L98)):*
<details><summary><i>Previously, fluffle (Alex Bee) wrote…</i></summary><blockquote>

You should test len(currCmd) + len(args[i]) +1 does not exceed the limit; currently if args[i] is very long it will be appended and exceed the limit. Figuring out what to do when len(args[i]) > splitLen is left as an exercise for the reader ;-)
</blockquote></details>

Sorry, among other changes, it escaped me
___
*[client/handlers.go, line 110 at r1](https://reviewable.io/reviews/fluffle/goirc/116#-MxhzAVQ9dDaAo5uLHYz:-MxkHhlY0-GO_4sKtV9h:bkg6du3) ([raw file](https://github.com/fluffle/goirc/blob/abfcc6aac2d081744d04b65ca0600dfde197f9c1/client/handlers.go#L110)):*
<details><summary><i>Previously, fluffle (Alex Bee) wrote…</i></summary><blockquote>

Also this needs a relatively exhaustive test to ensure the negotiation state machine is followed correctly.
</blockquote></details>

Do you mean a test using a mock connection?

**Review by fluffle — CHANGES_REQUESTED** [review]
Thanks for sticking with this, sorry to be a pedant when it comes to code review. Habits from work die hard :-)

I probably won't be able to take another look at this until Monday evening FYI, so there's no rush to address comments.

> *[Reviewable](https://reviewable.io/reviews/fluffle/goirc/116#-:-MxtBPb3A7HEioeQ3cJm:b6cxsa5)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @fluffle and @ostafen)

___
*[client/commands.go, line 90 at r2](https://reviewable.io/reviews/fluffle/goirc/116#-Mxk65E2CVdqvMeRJ2Vi:-MxtAV0d958cvaU_BWEX:bm1qxfk) ([raw file](https://github.com/fluffle/goirc/blob/b619c78dfa84485b8a58becf93872230a5a4e69a/client/commands.go#L90)):*
<details><summary><i>Previously, ostafen wrote…</i></summary><blockquote>

I think both solutions are good in terms of readability. I would go for my solution only for a matter of compactness and because I don't really like dealing with bidimensional slices when possible.
</blockquote></details>

No worries. I had a similar nagging feeling about the two nested for loops testing the same condition, but y'know... if it works (and has tests, hint) it's fine :-)
___
*[client/commands.go, line 95 at r2](https://reviewable.io/reviews/fluffle/goirc/116#-Mxk5VE46br7j9H2xHOb:-Mxt9CSeEdFW3C7qMMEB:bun5kst) ([raw file](https://github.com/fluffle/goirc/blob/b619c78dfa84485b8a58becf93872230a5a4e69a/client/commands.go#L95)):*
<details><summary><i>Previously, ostafen wrote…</i></summary><blockquote>

Yes, it was done precisely for that
</blockquote></details>

This feels like an example of functions that are too tightly coupled -- you have to know that cmdPrefix is expected to end in a : (or suffix your own space) to use it correctly. So, really, it only exists for its current usage. If splitCommand simply dealt with turning a list of args into a list of space-separated args not longer than a given limit, it would be more generally useful.

I would recommend changing the function signature to be splitCommand(args []string, maxLen int) []string, and dealing with the concatenation of the command prefix in func Cap. This function will be reusable for other cases where we might need to split data across multiple lines, and it will not have an unexpected subtle behaviour that could lead to bugs in the future.
___
*[client/handlers.go, line 110 at r1](https://reviewable.io/reviews/fluffle/goirc/116#-MxhzAVQ9dDaAo5uLHYz:-MxtB9kDD_KA4OkIDqck:b-p5pmlu) ([raw file](https://github.com/fluffle/goirc/blob/abfcc6aac2d081744d04b65ca0600dfde197f9c1/client/handlers.go#L110)):*
<details><summary><i>Previously, ostafen wrote…</i></summary><blockquote>

Do you mean a test using a mock connection?
</blockquote></details>

Yeah, there are plenty of examples in the library to cargo-cult from. For this kind of protocol negotiation I'd expect to see all of the examples from the spec implemented as unit tests, at the very least. I'm sure there are other edge cases that should be covered too.

**Review by ostafen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/fluffle/goirc/116)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @fluffle and @ostafen)

___
*[client/commands.go, line 95 at r2](https://reviewable.io/reviews/fluffle/goirc/116#-Mxk5VE46br7j9H2xHOb:-MxtJsUACqTaO4W-hpNw:b-612t21) ([raw file](https://github.com/fluffle/goirc/blob/b619c78dfa84485b8a58becf93872230a5a4e69a/client/commands.go#L95)):*
<details><summary><i>Previously, fluffle (Alex Bee) wrote…</i></summary><blockquote>

This feels like an example of functions that are too tightly coupled -- you have to know that cmdPrefix is expected to end in a : (or suffix your own space) to use it correctly. So, really, it only exists for its current usage. If splitCommand simply dealt with turning a list of args into a list of space-separated args not longer than a given limit, it would be more generally useful.

I would recommend changing the function signature to be splitCommand(args []string, maxLen int) []string, and dealing with the concatenation of the command prefix in func Cap. This function will be reusable for other cases where we might need to split data across multiple lines, and it will not have an unexpected subtle behaviour that could lead to bugs in the future.
</blockquote></details>

To tell the truth, I don't agree this point.  You don't have to know that your command ends with a ":", from a user perspective, you only have to know that the comma separated list of args is directly concatenated to your cmdPrefix. You are free to adapt your prefix to this convention. Putting a specific string to separate cmdPrefix and args would make functions tightly coupled.
For sure this functions doesn't cover all possible scenario where you could may need command splitting, but I think it could be used also in other cases.

Regarding the signature, I agree. I was undecided about including maxLen as an argument, because I couldn't find any case where you may not want to use the maximum allowed len.

**Comment by ostafen** [comment]
I noticed only now that all variables tracking state are stored in the StateTracker. So I imagine that I should put the supportedCaps and currCaps variables there. Do you agree? @fluffle

**Review by ostafen — COMMENTED** [review]
@fluffle: I added the sort.Strings call in order to make assertion at line 474 of file handlers_test always work. I don't like to inject this responsibility on code, but I couldn't find any other alternative.

**Review by fluffle — CHANGES_REQUESTED** [review]
Sorting is inevitable when dealing with map iteration

> *[Reviewable](https://reviewable.io/reviews/fluffle/goirc/116#-:-MyCXwmH-DiUq1W-uCy7:b7efntr)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @fluffle and @ostafen)

___
*[client/commands.go, line 95 at r2](https://reviewable.io/reviews/fluffle/goirc/116#-Mxk5VE46br7j9H2xHOb:-MyCUZkm6Nh_Gt5v7Kpm:b-gu0hky) ([raw file](https://github.com/fluffle/goirc/blob/b619c78dfa84485b8a58becf93872230a5a4e69a/client/commands.go#L95)):*
<details><summary><i>Previously, ostafen wrote…</i></summary><blockquote>

To tell the truth, I don't agree this point.  You don't have to know that your command ends with a ":", from a user perspective, you only have to know that the comma separated list of args is directly concatenated to your cmdPrefix. You are free to adapt your prefix to this convention. Putting a specific string to separate cmdPrefix and args would make functions tightly coupled.
For sure this functions doesn't cover all possible scenario where you could may need command splitting, but I think it could be used also in other cases.

Regarding the signature, I agree. I was undecided about including maxLen as an argument, because I couldn't find any case where you may not want to use the maximum allowed len.
</blockquote></details>

Sure, your argument makes sense. But you're not arguing against what I asked you to do, you're arguing against a point of your own devising. 

I didn't ask you to add "a specific string to separate cmdPrefix and args". I recommended "dealing with the concatenation of the command prefix in func Cap". Splitting a list of strings into space-concatenated chunks whose total length does not exceed a predefined limit is one task. Sticking a prefix onto each of these chunks is a different task, and one that does not necessarily need to be *coupled* to the first. The Cap function requires that both tasks take place, but other functions may not.

My suggestion would also make your tests simpler because there would be no need to parse a Line back out of cmd so you can have a special-case check to ensure that tests only failed if there's more than one arg per line. That complexity arises because of the two relatively orthogonal tasks that splitCommand takes on right now.

Now I'm gonna preach a bit because I think it's valuable you hear this:

Saying things like "you only have to know X", "you are free to adapt [...] to this convention", or "for sure this function doesn't cover all possible scenarios" is you making assumptions about other people's knowledge of the code that may not always hold true. Good defensive coding practice seeks to reduce or eliminate the need to read the code to know about these sorts of behaviours. You should be able to correctly infer the behaviour of a function from its signature and function docstring, so that you don't have to peek behind these abstractions to write bug free code using that function.

Any time you catch yourself saying "you only have to know X" you need to check the assumptions you're making. Figure out the behaviour of the code when people who don't know X use it incorrectly. Usually that'll cause a bug down the line sometime.
___
*[client/commands_test.go, line 221 at r6](https://reviewable.io/reviews/fluffle/goirc/116#-MyCYBC-AKk_RPgSpVML:-MyCYBC-AKk_RPgSpVMM:bddwa4x) ([raw file](https://github.com/fluffle/goirc/blob/70a85c08f663fc5a60e8a3568709842800647ef5/client/commands_test.go#L221)):*
> ```Go
> 				line := ParseLine(cmd)
> 				if len(line.Args) > 1 { // len(cmd) can exceed maxLen only if cmd includes a single argument.
> 					t.Fatalf("maxLen = %d, but len(cmd) = %d", maxLen, len(cmd))
> ```

You should use Errorf rather than Fatalf here.
___
*[client/handlers.go, line 113 at r6](https://reviewable.io/reviews/fluffle/goirc/116#-MyCkIJQ5ocjzjfSDM2O:-MyCkIJQ5ocjzjfSDM2P:b-b6ehso) ([raw file](https://github.com/fluffle/goirc/blob/70a85c08f663fc5a60e8a3568709842800647ef5/client/handlers.go#L113)):*
> ```Go
> 	c.mu.Lock()
> 	for _, cap := range caps {
> 		c.caps[cap] = true
> ```

The protocol allows for capabilities to be disabled by prefixing them with "-" -- you should detect that here and set the cap to false instead of true.



_Code quote:_
```Go
cap
```
___
*[client/handlers_test.go, line 476 at r6](https://reviewable.io/reviews/fluffle/goirc/116#-MyChE-l4xnIMSqGKgR_:-MyChE-l4xnIMSqGKgRa:b-1v50wu) ([raw file](https://github.com/fluffle/goirc/blob/70a85c08f663fc5a60e8a3568709842800647ef5/client/handlers_test.go#L476)):*
This is not protocol compliant. The protocol says:

>   The capability identifier set must be accepted as a whole, or rejected entirely.

I assume you're trying to test both ACK and NAK at the same time? I think you can trigger a second round of negotiation with c.Cap(CAP_LS) and have the server respond differently but still in a protocol compliant fashion without having to write another test.

The protocol allows for CAP REQ and CAP ACK/NAK as part of the normal flow of commands after registration too. I *think* your code will do the right thing if a library user sends Cap(CAP_REQ, "random", "capabilities") but you should write tests to validate this.

The protocol also says:

>   The END subcommand signals to the server that capability negotiation is complete and requests that the server continue with client registration. If the client is already registered, this command MUST be ignored by the server.

I guess it's fine for this implementation to reply with CAP END even after registration is complete. I note that we don't track "registration complete" in h_001 so it's potentially hard to inhibit responding with CAP END outside of registration.



_Code quote:_
```Go
	s.nc.Send("CAP * ACK cap2")
	s.nc.Send("CAP * NAK cap4")
```

**Review by fluffle — CHANGES_REQUESTED** [review]
Looking good now, just a couple of minor things.

> *[Reviewable](https://reviewable.io/reviews/fluffle/goirc/116#-:-MyHL7Ri5XI_R3YMFW0i:b3m1rmz)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @fluffle and @ostafen)

___
*[client/commands.go, line 95 at r2](https://reviewable.io/reviews/fluffle/goirc/116#-Mxk5VE46br7j9H2xHOb:-MyHHLE90V1bxLtN2tUW:b-qrsi0y) ([raw file](https://github.com/fluffle/goirc/blob/b619c78dfa84485b8a58becf93872230a5a4e69a/client/commands.go#L95)):*
<details><summary><i>Previously, fluffle (Alex Bee) wrote…</i></summary><blockquote>

Sure, your argument makes sense. But you're not arguing against what I asked you to do, you're arguing against a point of your own devising. 

I didn't ask you to add "a specific string to separate cmdPrefix and args". I recommended "dealing with the concatenation of the command prefix in func Cap". Splitting a list of strings into space-concatenated chunks whose total length does not exceed a predefined limit is one task. Sticking a prefix onto each of these chunks is a different task, and one that does not necessarily need to be *coupled* to the first. The Cap function requires that both tasks take place, but other functions may not.

My suggestion would also make your tests simpler because there would be no need to parse a Line back out of cmd so you can have a special-case check to ensure that tests only failed if there's more than one arg per line. That complexity arises because of the two relatively orthogonal tasks that splitCommand takes on right now.

Now I'm gonna preach a bit because I think it's valuable you hear this:

Saying things like "you only have to know X", "you are free to adapt [...] to this convention", or "for sure this function doesn't cover all possible scenarios" is you making assumptions about other people's knowledge of the code that may not always hold true. Good defensive coding practice seeks to reduce or eliminate the need to read the code to know about these sorts of behaviours. You should be able to correctly infer the behaviour of a function from its signature and function docstring, so that you don't have to peek behind these abstractions to write bug free code using that function.

Any time you catch yourself saying "you only have to know X" you need to check the assumptions you're making. Figure out the behaviour of the code when people who don't know X use it incorrectly. Usually that'll cause a bug down the line sometime.
</blockquote></details>

Thanks for putting up with my lecturing :-)
___
*[client/commands.go, line 321 at r7](https://reviewable.io/reviews/fluffle/goirc/116#-MyHK4vVE4VYGhotIQVb:-MyHK4vVE4VYGhotIQVc:b3vjvl3) ([raw file](https://github.com/fluffle/goirc/blob/c2f4dcb7edfcff469c8ed19e8947d358738f0626/client/commands.go#L321)):*
> ```Go
> 	} else {
> 		// make output predictable for testing
> 		sort.Strings(capabilities)
> ```

This sort.Strings should be in capSet.Slice, since that is where the randomness is creeping in.
___
*[client/handlers_test.go, line 476 at r6](https://reviewable.io/reviews/fluffle/goirc/116#-MyChE-l4xnIMSqGKgR_:-MyHHsB55kBwt8slh7MP:b-e3ubpj) ([raw file](https://github.com/fluffle/goirc/blob/70a85c08f663fc5a60e8a3568709842800647ef5/client/handlers_test.go#L476)):*
<details><summary><i>Previously, fluffle (Alex Bee) wrote…</i></summary><blockquote>

This is not protocol compliant. The protocol says:

>   The capability identifier set must be accepted as a whole, or rejected entirely.

I assume you're trying to test both ACK and NAK at the same time? I think you can trigger a second round of negotiation with c.Cap(CAP_LS) and have the server respond differently but still in a protocol compliant fashion without having to write another test.

The protocol allows for CAP REQ and CAP ACK/NAK as part of the normal flow of commands after registration too. I *think* your code will do the right thing if a library user sends Cap(CAP_REQ, "random", "capabilities") but you should write tests to validate this.

The protocol also says:

>   The END subcommand signals to the server that capability negotiation is complete and requests that the server continue with client registration. If the client is already registered, this command MUST be ignored by the server.

I guess it's fine for this implementation to reply with CAP END even after registration is complete. I note that we don't track "registration complete" in h_001 so it's potentially hard to inhibit responding with CAP END outside of registration.




</blockquote></details>

I think we can probably survive without NAK testing during registration.

**Review by ostafen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/fluffle/goirc/116)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @fluffle)

___
*[client/commands.go, line 321 at r7](https://reviewable.io/reviews/fluffle/goirc/116#-MyHK4vVE4VYGhotIQVb:-MyHS9hZ85_7BYl5Vvz8:buhp8pl) ([raw file](https://github.com/fluffle/goirc/blob/c2f4dcb7edfcff469c8ed19e8947d358738f0626/client/commands.go#L321)):*
> This sort.Strings should be in capSet.Slice, since that is where the randomness is creeping in.
Yeah, that's the right place :=)
___
*[client/handlers_test.go, line 476 at r6](https://reviewable.io/reviews/fluffle/goirc/116#-MyChE-l4xnIMSqGKgR_:-MyD8_CH5T-RAMJA9qS8:bnom0xk) ([raw file](https://github.com/fluffle/goirc/blob/70a85c08f663fc5a60e8a3568709842800647ef5/client/handlers_test.go#L476)):*
<details><summary><i>Previously, fluffle (Alex Bee) wrote…</i></summary><blockquote>

I think we can probably survive without NAK testing during registration.
</blockquote></details>


It should not be critical, since we simply return a CAP END

**Review by fluffle — APPROVED** [review]
Awesome. One final request -- can you rebase and squash all of these down into a single commit before I merge it?

> *[Reviewable](https://reviewable.io/reviews/fluffle/goirc/116#-:-MyHt5Vh3u3kUyicJJ_S:b5r1w2t)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @fluffle)

**Review by fluffle — APPROVED** [review]
:lgtm:

Sorry for the spam, I have forgotten some of how to use reviewable :-)

> Reviewed 1 of 3 files at r2, 2 of 4 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fluffle/goirc/116#-:-MyHtbFg9llEjzKK8tK5:b-39oe47)* status: all files reviewed, 1 unresolved discussion (waiting on @fluffle)

**Review by fluffle — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/fluffle/goirc/116)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ostafen)

**Comment by ostafen** [comment]
Done! I respost this because maybe you didn't see this on reviewable: 

"EDIT: It seems you missed this message (or, maybe I missed your reply): "I noticed only now that all variables tracking state are stored in the StateTracker. So I imagine that I should put the supportedCaps and currCaps variables there. Do you agree?" @fluffle"

**Review by fluffle — APPROVED** [review]
Ah, sorry, I did totally miss that. No need to apologise!

The state tracker is for channel and nick state. It's completely fine to run the client without it if you don't care about that sort of thing. I don't think this is quite the same -- it does track some state about the *connection*, but not the network's inhabitants. I think it's fine to leave this in the main client package for now. If it gets too unwieldy and you want further separation of code in the future, a separate package "cap" might make sense.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fluffle/goirc/116#-:-MyOM7K21E3i0NgS1OpZ:bloc26j)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ostafen)

**Comment by fluffle** [comment]
Thank you for all your effort on this!

**Comment by fluffle** [comment]
I've tagged v1.2.0 so this capability (ha) can be required in go.mod files.

**Pull request merged**
