### PR TITLE
Added proxy support

### PR DESCRIPTION
**Pull request by scrapbird**
Modified the connection.go file a little to add support for proxying connections. Also simplified the SSL port logic a little bit in the process.

### CODE REVIEW

**Comment by fluffle** [comment]
Very nice. The use of tls.Client does help simplify things.

One request before I merge this: can you just have one Config variable "Proxy string" which causes the client to use the proxy if conn.cfg.Proxy != ""? SSL requires a separate bool because supplying a non-nil SSLConfig is optional, but here you don't need it.

**Comment by scrapbird** [comment]
Sweet, all changed.

**Comment by fluffle** [comment]
LGTM, thanks a lot!

**Comment by scrapbird** [comment]
Anytime.

**Pull request merged**
