### PR TITLE
Fix TestSTRaces panics

### PR DESCRIPTION
**Pull request by soul9**
since GetNick returns nil, calling methods on it will generate runtime panics (same with GetChannel vs. NewChannel).
This might defeat the purpose of the test, in which case it should be changed in a more fundamental way.

### CODE REVIEW

**Comment by fluffle** [comment]
I wrote this test before Go 1.5 changed goroutine ordering behaviour. It tests for race conditions I am reasonably sure are fixed now, since everything is behind locks. The best thing to do is probably just delete the test -- I suspect your change might prevent the "expected" races from happening. Having said that, if there's one thing I'm sure of, it's that I am bad at concurrency :-)

**Comment by soul9** [comment]
Yeah, that's what I thought. just put this here to make tests pass. That test doesn't really make sense except if you're willing to check for the values being nil.

**Comment by fluffle** [comment]
I just nuked the test instead.

**Comment by soul9** [comment]
exact same commit but whatever

**Comment by fluffle** [comment]
Oh, duh, I thought this still contained the fix. Sorry, not 100% paying attention :-)

**Comment by soul9** [comment]
yeah. happens to the best ;)

**Pull request closed without merging**
