### PR TITLE
h_324 mode reply handler: check array bounds before indexing

### PR DESCRIPTION
**Pull request by soul9**
I crossed this bug while playing with the code. the panic recovery caught it so the program didn't exit, but I'm not really sure how well that works.

### CODE REVIEW

**Comment by fluffle** [comment]
Urgh.

AIUI any response to RPL_CHANNELMODEIS that doesn't contain exactly 3 space-separated components is violating RFC1459. There are plenty of unchecked slice indexes in handlers.go and state_handlers.go, because there is an implicit assumption that if those indexes hit a nonexistent element of the underlying array, the server is not speaking RFC compliant IRC protocol and the best thing to do is panic. But! It probably doesn't hurt to be careful, and if we are going to do this just to be careful, it makes sense to do it in every handler that could be affected, IMO.

So, thanks for the PR, but I think we should either check all the index operations for line.Args >= 1 in all the handlers in this client, or check none of them. We can guarantee that line.Args contains at least 1 element because otherwise the parsing would have panicked in line.go.

What do you think? Are you OK with increasing the scope of this PR?

**Comment by soul9** [comment]
sure. I'll be on the hunt for unchecked indexing operations in the near future then, and update the PR when I am confident I've got them all.
btw. the culprit is the ergonomadic irc server, so i'll try and find the bug in that too.
thanks

**Comment by fluffle** [comment]
On further investigation, I think the second and third parameter for RPL_CHANNELMODEIS are optional: if the channel modes don't require e.g. a key or a limit, then there's no need for any positional parameter beyond the first two, and if there's no modes set at all, the second parameter probably doesn't need to be there. The slice I'm doing should be fine if the third parameter does not exist: http://play.golang.org/p/ksoao0f-H5

This means that ergonomadic (I'd not heard of this before, but yay, a Go IRCd) is sending just the channel name. I am reasonably sure this means that your channel has no modes at all.

UnrealIRCd sends <channel><space><plus><space> in response when the channel has no modes:

    :bing.pl0rt.org 324 GoTest #fn3jt + 

Efnet and freenode omit the trailing space but maintain the +:

    :irc.choopa.net 324 GoTest #fn3jt +
    :wolfe.freenode.net 324 GoTest #fn3jt +

Ergonomadic definitely only includes the + if the mode string is not "": https://github.com/edmund-huber/ergonomadic/blob/master/irc/channel.go#L108

The robustness principle indicates that we should probably accept the complete lack of a channel mode (even a +) here. Passing an empty string as the second argument to st.ChannelModes() has the same behaviour as passing the string "+", so that's what we should do here. Are you interested in changing your PR to accomplish this?

I wonder if it is worth filing an issue or PR against ergonomadic too, to bring their behaviour more in line with other IRCds?

**Comment by soul9** [comment]
I have an ssl PR in the pipes for ergonomadic so i'll try to smuggle this smallish fix with it.

**Comment by soul9** [comment]
Do you still think I should increase the scope of the PR? I have a WIP with all handlers in handlers.go checking their bounds before indexing slices.

**Comment by soul9** [comment]
sorry about this.

**Comment by fluffle** [comment]
It's cool, thanks for the work :-)

**Pull request closed without merging**
