### PR TITLE
client/connection: fix deadlock with double shutdown

### PR DESCRIPTION
**Pull request by StalkR**
second attempt :) I had forgotten the unlock in the return case.

### CODE REVIEW

**Comment by fluffle** [comment]
I'll be the first to admit my grasp of concurrency problems is poor, but I don't get where the deadlock is. Can you explain it in words of no more than one syllable for my benefit please?

**Comment by StalkR** [comment]
My understanding is:
- consider we are in a flood condition (easier to trigger), our first goroutine is on `conn.write()`, blocked on `time.After` because of flood: https://github.com/fluffle/goirc/blob/master/client/connection.go#L367
- in a second goroutine a disconnect happens, caught by `conn.recv` which calls `conn.shutdown()` (https://github.com/fluffle/goirc/blob/master/client/connection.go#L314) we get the `conn.mu` lock, then wait on `conn.wg.Wait()` for the others to finish
- `conn.write` gets out of its `time.After`, tries `conn.io.WriteString` which fails, then tries to call `irc.shutdown()` (https://github.com/fluffle/goirc/blob/master/client/connection.go#L371) which is blocked on its mutex (https://github.com/fluffle/goirc/blob/master/client/connection.go#L406) - therefore cannot return
- that `conn.write` was called by `conn.send` (https://github.com/fluffle/goirc/blob/master/client/connection.go#L292) so it's still blocked on that, and cannot execute its `defer conn.wg.Done()` - where we are stuck

**Comment by StalkR** [comment]
In simple words: we have to release `conn.mu` before `conn.wg.Wait()` because `conn.shutdown()` can be called multiple times by different goroutines.

**Comment by fluffle** [comment]
Ahh, yes, I see, thanks for taking the time to explain it to me :-)

It feels a bit like you're working around the problem with your patch. In my plague-infested state I can't figure a way to test the deadlock condition directly, but could you have a look at the "deadlock-fix" branch and see if it solves your problem? I think dealing with the deadlock directly rather than adding more byzantine locking semantics is a better idea.

**Comment by StalkR** [comment]
Ok, traveling so I'll look at it next week.

**Comment by StalkR** [comment]
Cool, so I agree on your fix for `conn.wg` deadlock but there's still another deadlock with `conn.mu` which I highlighted in my PR with this comment: https://github.com/fluffle/goirc/pull/58/files#diff-a7051728cae32ddb194585af61fb784cR422

Basically:
- `shutdown()` keeps `conn.mu` lock while dispatching the `DISCONNECTED` event
- a disconnected handler might want to look at `Me()` to save the state (e.g. to [save](https://github.com/StalkR/goircbot/blob/master/bot%2Fbot.go#L74) the channels that the bot was on to join them at the next connection) before `initialise()` resets it as part of `shutdown()`
- but `Me()` wants `conn.mu` lock (https://github.com/fluffle/goirc/blob/deadlock-fix/client/connection.go#L171), so it deadlocks

My proposal (as it was in my original pull request) is to release the lock before dispatching the event, and have `initialise()` take the lock again.

Other ideas:
- remove `initialise()` from `shutdown()`: it's not clear to me why we need it, instead we could leave everything as-is and only call `initialise()` when a new connection is made (or not call it at all, since values will be overwritten anyway)
- if I recall correctly this `conn.mu` lock protecting `Me()` appeared when you refactored with it to remove some races; if there's a way we can remove it, that would solve the issue

**Comment by StalkR** [comment]
So: LGTM to merge your `deadlock-fix` branch in `master`, fixing the deadlock on double-shutdown, and I updated this PR with my proposed fix for `conn.mu` deadlock during event dispatch. PTAL.

**Comment by fluffle** [comment]
Been on vacation for a week, sorry. Just pushed that merge.

I like removing `initialise()` from `shutdown()` as part of the solution to the other deadlock problem. You're absolutely right that there doesn't seem to be any good reason for it to be there. I'm not sure whether the lock in `Me()` can be removed. go test -race passes without it being there and while I think there's a theoretical race if someone is enabling or disabling state tracking while calling `Me()` I don't think it's particularly dangerous.

I've pushed some more changes to deadlock-fix. I feel kinda bad completely disregarding your PR after all the work you did tracking this down, and I am really grateful for the effort you have put in explaining my shortcomings to me, but it seemed lower friction to just make the changes I thought necessary right now instead of going through a code review cycle.

**Comment by StalkR** [comment]
Awesome! Tested with goircbot, LGTM to merge that last commit on deadlock-fix to master.

Don't be sorry for being in vacation :) And don't feel bad about not accepting the PR, I care more about fixing the issues properly I'm just happy to help. I like to consider a PR as another way to illustrate the issues previously explained in text, or at best a suggestion, but you know the code best. Since you have a better knowledge of the code, you know the best ways to fix the issues we uncovered, and fix the tests - which I didn't do. As for pushing your changes to the deadlock-fix branch directly, I like and that's actually kind of a code review before shipping to master if you think about it.

**Comment by fluffle** [comment]
I should think things through a little more: deferring the dispatch of DISCONNECTED, while neat, results in it being dispatched twice occasionally. I've fixed that and merged deadlock-fix again. Until the next bug!

**Comment by StalkR** [comment]
Good catch, then yes let's go back to my initial solution with explicit unlocks. That surely triggered a double reconnect for goircbot, which I likely missed because too fast. Thanks!

**Pull request closed without merging**
