### PR TITLE
Issue 98

### PR DESCRIPTION
**Pull request by Oshuma**
This change is [Reviewable](https://reviewable.io/reviews/fluffle/goirc/99)

### CODE REVIEW

**Comment by ripcurld0** [comment]
That's odd to me. I was expecting `v.IsValid()` to return false if `nm` will be a pointer to `nil`.
I might get this if I do the following, which doesn't seem right to me:
```
var nickMode *goirc.NickMode
nickMode.String()
```
I am not against this change, though.

**Comment by fluffle** [comment]
I would prefer the explicit nil check, for consistency, i.e.

```go
if nm == nil {
    return "No modes set"
}
```

at the start of String(). Thanks for pointing out this omission! Have you looked for other places where I might have failed in this manner? :-)

**Comment by Oshuma** [comment]
I initially had a nil check, but it wouldn't compile, so I changed it to `IsValid()`.  Haven't looked over any of the other code, since just this issue was keeping my bot from compiling.

**Comment by ripcurld0** [comment]
@Oshuma Can you copy-paste the compilation error?

**Comment by ripcurld0** [comment]
@fluffle - Running `grep -rn --color "*NcikMode) "` gives:
```bash
./state/nick.go:146:func (nm *NickMode) Copy() *NickMode {
./state/nick.go:153:func (nm *NickMode) Equals(other *NickMode) bool {
./state/nick.go:183:func (nm *NickMode) String() string {
```

In `Equals` it seems OK because we are using `reflect.DeepEqual`.
So I guess this patch covers it up.

**Comment by Oshuma** [comment]
@ripcurld0 Actually I misspoke.  It wasn't a compilation error with the library, just that panic of `call of reflect.Value.Type on zero Value` I mentioned in Issue #98.

**Comment by ripcurld0** [comment]
@Oshuma ooh, so what we meant is instead of doing:
```go
v := reflect.Indirect(reflect.ValueOf(nm))
if v.IsValid() {
...
}
```

Do the check before `v := reflect.Indirect(reflect.ValueOf(nm))`. Like this:

```go
if nm == nil {
    return str
}
v := reflect.Indirect(reflect.ValueOf(nm))
```

@fluffle correct me if I'm wrong.

**Comment by Oshuma** [comment]
@ripcurld0 Yea, that seems to work, although I think the `IsValid()` check should still be used.

**Comment by ripcurld0** [comment]
According to the docs [here](https://golang.org/pkg/reflect/#Indirect):

>  Indirect returns the value that v points to. If v is a nil pointer, Indirect returns a zero Value. If v is not a pointer, Indirect returns v. 

So it looks like unnecessary to do that. Although, it's nice to be extra sure nothing will fail.
I will let @fluffle to decide what to do as he is the maintainer. 👼 

Thanks.

**Comment by fluffle** [comment]
https://play.golang.org/p/GAN9uT4Zxi

I don't believe the check for IsValid() is necessary. The panic arises because ValueOf(nil) produces the zero Value:

https://golang.org/pkg/reflect/#ValueOf

This is different from a zero value of a specific type, as created by literals and reflect.Zero:

https://golang.org/pkg/reflect/#Zero

It's perfectly safe to call v.Type() on a normal zero value, but not the zero Value.

**Comment by fluffle** [comment]
Hi,

I'm sorry for leaving this to languish, I've not had the time to follow up on it. I'd be happy to merge this if you swap the isValid() check for a nil check at the start of String instead.

**Comment by Oshuma** [comment]
@fluffle Sure thing, I'll make that change when I get a chance and update this PR/branch.

**Comment by fluffle** [comment]
Ping? I'd still be happy to merge this with the suggested changes made.

**Comment by Oshuma** [comment]
@fluffle Sorry man, I've been a bit busy and haven't made those changes yet.  Not sure when I'll be able to get around to it, so you can go ahead and make the change or I can do it when I get time and update this PR.

**Comment by fluffle** [comment]
Added nil checks in the various reflect-using String methods.

**Pull request closed without merging**
